version: "3.9"

services:
  mariadb:
    build:  ./requirements/mariadb
    image:  mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
      - ./requirements/mariadb/conf/my.cnf:/etc/mysql/my.cnf:ro
    secrets:
      - mariadb_root_password
      - mariadb_password
    networks:
      - net
    restart: on-failure

  wordpress:
    build:  ./requirements/wordpress
    image:  wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wp:/var/www/html
    depends_on:
      - mariadb
    secrets:
      - mariadb_password
      - wp_admin_password
      - wp_guest_password
    expose:
      - "9000"
    networks:
      - net
    restart: on-failure

  nginx:
    build:  ./requirements/nginx
    image: nginx
    container_name: nginx
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - wp:/var/www/html:ro
    depends_on:
      - wordpress
    networks:
      - net
    restart: on-failure

  redis:
    build:  ./requirements/bonus/redis
    image:  redis
    container_name: redis
    depends_on:
      - wordpress
    ports:
    - "6379:6379"
    env_file:
      - .env
    volumes:
      - wp:/var/www/html
    networks:
      - net
    restart: on-failure

  ftp:
    build: ./requirements/bonus/ftp
    image:  ftp
    container_name: ftp
    depends_on:
      - wordpress
    secrets:
      - ftp_password
    ports:
      - "21:21"
      - "50000-50010:50000-50010"
    env_file:
      - .env
    volumes:
      - wp:/var/www/html
    networks:
      - net
    restart: on-failure

  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    container_name: adminer
    networks:
      - net
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    restart: on-failure

  vue-static:
    build: ./requirements/bonus/vue-static
    image: vue-static
    container_name: vue-static
    depends_on:
      - nginx
    ports:
      - "8443:443"
    volumes:
      - ./requirements/bonus/vue-static/vue-app/dist:/usr/share/nginx/html:ro
      - ./requirements/bonus/vue-static/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - net
    restart: on-failure

  cadvisor:
    build: ./requirements/bonus/cadvisor
    image: cadvisor
    container_name: cadvisor
    ports:
       - "8000:8080"
    networks:
     - net
    volumes:
      - /:/rootfs
      - /var/run:/var/run
      - /sys:/sys
      - /var/lib/docker/:/var/lib/docker
    restart: on-failure

volumes:
  db:
    driver_opts:
      type: 'none'
      o: bind
      device: /home/tiizuka/data/mysql
  wp:
    driver_opts:
      type: 'none'
      o: bind
      device: /home/tiizuka/data/wordpress

secrets:
  mariadb_root_password:
    file: ../secrets/mariadb_root_password.txt
  mariadb_password:
    file: ../secrets/mariadb_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_guest_password:
    file: ../secrets/wp_guest_password.txt
  ftp_password:
    file: ../secrets/ftp_password.txt

networks:
  net:
    driver: bridge
